name: Java CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Only test on supported JDKs: https://adoptopenjdk.net/support.html
        # JDK15 is no longer available in github actions; Groovy 2.5.10 isn't compatible with JDK 16+
        # Vaadin-Boot is only compatible with JDK 11+
        # only test on 11
        java: [11]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
    - name: Build with Gradle
      run: ./gradlew --stacktrace --info --no-daemon
